### ISSUE TITLE
How to build the first application?

### ISSUE THREAD

**Issue by StekolschikovV** [wojtkowiak/meteor-desktop#122]
Hello!

I'm a beginner developer. I need to build the application into an executable (ex x64). Tell me what I'm doing wrong:

```
meteor create build2
cd build2
npm install --save-dev meteor-desktop
npm run desktop -- init
```

Then I tried to build the application:

```
npm run desktop -- build
npm run desktop --build-meteor   
```
And other commands from the description.

The result is usually this:

> meteor-desktop                                                                                                        METEOR-DESKTOP v0.8.1                                                                                                   REMINDER: your Meteor project should be running now on port 3000                                                                                                                    INFO  index:  initializing                                  INFO  electronApp:  scaffolding                             VERBOSE  desktop:  checking .desktop existence              VERBOSE  meteorApp:  updating .meteor/.gitignore            VERBOSE  meteorApp:  desktopHCP is enabled, checking for required packages                                              VERBOSE  electronAppScaffold:  clearing desktop-build       VERBOSE  electronAppScaffold:  creating C:\Users\steko\Desktop\DEV\build2\.meteor\desktop-build\app                     VERBOSE  electronAppScaffold:  copying skeleton app         VERBOSE  electronAppScaffold:  writing package.json         VERBOSE  electronApp:  updating package.json fields         DEBUG  electronApp:  writing updated package.json           INFO  electronApp:  updating list of package.json's dependencies                                                        DEBUG  electronApp:  merging settings.json[dependencies]    DEBUG  electronApp:  merging settings.json[plugins]         DEBUG  electronApp:  merging dependencies from modules      DEBUG  electronApp:  writing updated package.json           VERBOSE  electronApp:  calculating compatibility version    DEBUG  electronApp:  meteor-desktop compatibility version is  0.8                                                       DEBUG  electronApp:  .desktop compatibility version is  0   INFO  electronApp:  installing dependencies                 DEBUG  electronApp:  running npm prune to wipe unneeded dependencies                                                    VERBOSE  electronApp:  executing npm prune                  VERBOSE  electronApp:  executing npm install                WARN  electronApp:  native modules rebuild is turned off, be sure to turn it on if you added any native node modules    VERBOSE  electronApp:  copying .desktop to temporary location                                                           DEBUG  electronApp:  updating settings.json fields          INFO  desktop:  calculating hash version from .desktop contents                                                         VERBOSE  desktop:  calculated .desktop hash version is 30e487b47944ca6bdf90989b29643b5bd9b9a4f6                         INFO  electronApp:  excluding files from packing            INFO  electronApp:  transpiling and uglifying               INFO  electronApp:  packing .desktop to asar                VERBOSE  electronApp:  clearing temporary .desktop          INFO  meteorApp:  checking for any mobile platform          INFO  meteorApp:  building meteor app                       DEBUG  meteorApp:  clearing build dir                       INFO  meteorApp:  acquiring index.html                      ERROR  meteorApp:  error while trying to download index.html for web.cordova, be sure that you are running a mobile target or with --mobile-server:  { FetchError: request to http://127.0.0.1:3000/__cordova/index.html failed, reason: connect ECONNREFUSED 127.0.0.1:3000                                    at ClientRequest.<anonymous> (C:\Users\steko\Desktop\DEV\build2\node_modules\node-fetch\index.js:133:11)                at emitOne (events.js:96:13)                                at ClientRequest.emit (events.js:188:7)                     at Socket.socketErrorListener (_http_client.js:310:9)       at emitOne (events.js:96:13)                                at Socket.emit (events.js:188:7)                            at emitErrorNT (net.js:1277:8)                              at _combinedTickCallback (internal/process/next_tick.js:80:11)                                                          at process._tickCallback (internal/process/next_tick.js:104:9)                                                        name: 'FetchError',                                         message: 'request to http://127.0.0.1:3000/__cordova/index.html failed, reason: connect ECONNREFUSED 127.0.0.1:3000',   type: 'system',                                             errno: 'ECONNREFUSED',                                      code: 'ECONNREFUSED' }                                                                                                npm ERR! Windows_NT 10.0.15063                              npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "desktop" "--just-run"                                    npm ERR! node v6.11.2                                       npm ERR! npm  v3.10.10                                      npm ERR! code ELIFECYCLE                                    npm ERR! build2@ desktop: `meteor-desktop`                  npm ERR! Exit status 1                                      npm ERR!                                                    npm ERR! Failed at the build2@ desktop script 'meteor-desktop'.                                                         npm ERR! Make sure you have the latest version of node.js and npm installed.                                            npm ERR! If you do, this is most likely a problem with the build2 package,                                              npm ERR! not with npm itself.                               npm ERR! Tell the author that this fails on your system:    npm ERR!     meteor-desktop                                 npm ERR! You can get information on how to open an issue for this project with:                                         npm ERR!     npm bugs build2                                npm ERR! Or if that isn't available, you can get their info via:                                                        npm ERR!     npm owner ls build2                            npm ERR! There is likely additional logging output above.                                                               npm ERR! Please include the following file with any support request:                                                    npm ERR!     C:\Users\steko\Desktop\DEV\build2\npm-debug.log

[npm-debug.log](https://github.com/StekolschikovV/meteor-desktop/blob/master/npm-debug.log)
[console log](https://github.com/StekolschikovV/meteor-desktop/blob/master/err.txt)
[git](https://github.com/StekolschikovV/meteor-desktop)

How to build an application?

**Comment by nzomedia** [comment]
I just tried your two last commands to be sure. And i had the error "connect ECONNREFUSED 127.0.0.1:3000'". What this means is that there's no process listening on the port 3000 of your computer (local host). In other words your Meteor project isn't running. You have to launch your project like this:
` meteor run --mobile-server http://127.0.0.1:3000`
_For meteor-desktop, the option **--mobile-server** is required._
The URL i'm using depends on your setup. But 127.0.0.1 is your local machine.

So once your server is started, you can now use any of meteor-desktop commands to make a package, build or launch a desktop app from your project. ie: `npm run desktop -- package http://127.0.0.1:3000`.
Notice how i am using the same URL  for --mobile-server and as the last parameter to npm run desktop. This is the ddp URL as stated in the help section of meteor-desktop [npm documentation]("https://www.npmjs.com/package/meteor-desktop#usage---help"). And it must be the same when you launch your project and when you build, package or create an installer.
By reading the doc you'll see where the build  or package or installer produced will be created.
