### ISSUE TITLE
[V0.12.0] Unhandled promise rejection when building 32-bit Windows installer with NSIS

### ISSUE THREAD

**Issue by KoenLav** [wojtkowiak/meteor-desktop#143]
When running v0.12.0 with --all-archs I receive the following error:

```
DEBUG  electronBuilder:  calling installOrRebuild from electron-builder for arch ia32
(node:8320) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'match' of undefined
(node:8320) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Building without --all-archs does work.

**Comment by wojtkowiak** [comment]
What platform and what is the target?

**Comment by KoenLav** [comment]
Building on Windows, target = all-archs or ia32

**Comment by wojtkowiak** [comment]
Sorry by target I meant if it is `squirrel`, `nsis` or sth else?

**Comment by KoenLav** [comment]
NSIS.

Apologies, misunderstood the question.

**Comment by wojtkowiak** [comment]
Could not reproduce it so far. Seems that it might be related to your dependencies. Could you paste the package.json from `.meteor/desktop-build`?

**Comment by KoenLav** [comment]
```
{
  "name": "App",
  "main": "app.asar/index.js",
  "dependencies": {
    "connect": "3.5.0",
    "server-destroy": "1.0.1",
    "connect-modrewrite": "0.9.0",
    "winston": "2.3.0",
    "find-port": "2.0.1",
    "rimraf": "2.5.4",
    "shelljs": "0.7.5",
    "lodash": "4.17.4",
    "request": "2.79.0",
    "queue": "4.0.1",
    "reify": "0.4.4",
    "send": "0.14.1",
    "fs-plus": "2.9.3",
    "meteor-desktop-splash-screen": "0.3.0",
    "electron-settings": "^3.1.1",
    "node-machine-id": "^1.1.9",
    "once": "^1.4.0"
  },
  "version": "2.7.2",
  "description": "App",
  "author": "App",
  "private": true
}
```

**Comment by KoenLav** [comment]
I can reproduce the error on every run, even if I delete .meteor/desktop-build before running.

```
INFO  electronApp:  packing skeleton app and node_modules to asar archive
DEBUG  electronApp:  moving node_modules to app dir
DEBUG  electronApp:  packing
DEBUG  electronApp:  moving node_modules back from app dir
DEBUG  electronApp:  deleting source files
DEBUG  electronBuilder:  moving node_modules out, because we have them already in app.asar
  • packaging       platform=win32 arch=x64 electron=1.7.9 appOutDir=.desktop-installer\win-unpacked
DEBUG  electronBuilder:  moving node_modules back
DEBUG  electronBuilder:  calling installOrRebuild from electron-builder for arch ia32
(node:6244) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'match' of undefined
(node:6244) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by wojtkowiak** [comment]
One more thing set the debug env var `DEBUG=electron-builder` we should see some more logs from electron-builder.

**Comment by KoenLav** [comment]
```
DEBUG  electronApp:  moving node_modules back from app dir
DEBUG  electronApp:  deleting source files
DEBUG  electronBuilder:  moving node_modules out, because we have them already in app.asar
  • packaging       platform=win32 arch=x64 electron=1.7.9 appOutDir=.desktop-installer\win-unpacked
  • spawning        command=C:\Users\user\PhpStormProjects\App\waiter\node_modules\7zip-bin-win\x64\7za.exe x -bd C:\Users\user\AppData\Local\electron\Cache\electron-v1.7.9-win32-x64.zip -aoa -oC:\Users\user\PhpStormProjects\App\waiter\.desktop-installer\win-unpacked

7-Zip (a) 18.01 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-01-28

Scanning the drive for archives:
1 file, 53893903 bytes (52 MiB)

Extracting archive: C:\Users\user\AppData\Local\electron\Cache\electron-v1.7.9-win32-x64.zip
--
Path = C:\Users\user\AppData\Local\electron\Cache\electron-v1.7.9-win32-x64.zip
Type = zip
Physical Size = 53893903

Everything is Ok

Files: 117
Size:       138386650
Compressed: 53893903
  • exited          command=7za.exe code=0 pid=5308
  • getPublishConfigsForUpdateInfo: no publishConfigs, detect using repository info
DEBUG  electronBuilder:  moving node_modules back
  • spawning        command=C:\Users\user\PhpStormProjects\App\waiter\node_modules\app-builder-bin-win\x64\app-builder.exe icon --format ico --root C:\Users\user\PhpStormProjects\App\waiter\build --root C:\Users\user\PhpStormProjects\App\waiter --out C:\Users\user\PhpStormProjects\App\waiter\.desktop-installer\.icon-ico --input .desktop/assets/meteor.ico
  • path doesn't exist        path=C:\Users\user\PhpStormProjects\App\waiter\build\.desktop\assets\meteor.ico
  • path resolved             outputFormat=ico path=C:\Users\user\PhpStormProjects\App\waiter\.desktop\assets\meteor.ico
  • exited          command=app-builder.exe code=0 pid=13584 out={"icons":[{"file":"C:\\Users\\user\\PhpStormProjects\\App\\waiter\\.desktop\\assets\\meteor.ico","size":0}]}
  • spawning        command=C:\Users\user\PhpStormProjects\App\waiter\node_modules\app-builder-bin-win\x64\app-builder.exe download-artifact --url https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-1.9.0/winCodeSign-1.9.0.7z --name winCodeSign-1.9.0 --sha512 cyhO9Mv5MTP2o9dwk/+qs0KvuO9CbDhjEJXA2ujpvhcsk5zmc+zY9iqiWXVzOuibTLYNC3qZiuFlJrrCT2kldw==
  • found existing            path=C:\Users\user\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-1.9.0
  • exited          command=app-builder.exe code=0 pid=15576 out=C:\Users\user\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-1.9.0
  • executing       file=C:\Users\user\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-1.9.0\rcedit.exe args=C:\Users\user\PhpStormProjects\App\waiter\.desktop-installer\win-unpacked\App.exe
--set-version-string FileDescription App --set-version-string ProductName App --set-version-string LegalCopyright Copyright © 2018 App --set-file-version 2.7.2 --set-product-version 2.7.2.0 --set-version-string InternalName App --set-version-string OriginalFilename  --set-version-string CompanyName App --set-icon C:\Users\user\PhpStormProjects\App\waiter\.desktop\assets\meteor.ico
  • executed        file=C:\Users\user\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-1.9.0\rcedit.exe
wine&sign: 0s 468ms
DEBUG  electronBuilder:  calling installOrRebuild from electron-builder for arch ia32
(node:5604) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'match' of undefined
(node:5604) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Possibly (un-)related: 

While running npm install in our project:
`warning "meteor-desktop > electron-builder-squirrel-windows@20.0.5" has unmet peer dependency "electron-builder-lib@~20.0.5"`

AND

```
INFO  meteorApp:  meteor build finished
INFO  electronApp:  built
DEBUG  electronBuilder:  calling build from electron-builder
  • electron-builder version=20.0.8
ERROR  electronBuilder:  error while building installer:  { Error: Cannot find module 'read-config-file'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at _load_readConfigFile (C:\Users\user\PhpStormProjects\App\waiter\node_modules\electron-builder-lib\out\util\config.js:166:30)
    at C:\Users\user\PhpStormProjects\App\waiter\node_modules\electron-builder-lib\src\util\config.ts:36:40
    at Generator.next (<anonymous>)
From previous event:
    at getConfig (C:\Users\user\PhpStormProjects\App\waiter\node_modules\electron-builder-lib\out\util\config.js:66:21)
```

**Comment by wojtkowiak** [comment]
Still not sure what is happening in your project but please test it now with `0.13.0` . If that does not help I am gonna probably need a small repro to check on my side.

**Comment by enuoCM** [comment]
@wojtkowiak I got a new error with 0.13.0.

```
DEBUG  electronBuilder:  moving node_modules out, because we have them already in app.asar
mv E:\app\.meteor\desktop-build\node_modules E:\app\.meteor\.desktop_node_modules
TypeError: fd must be a file descriptor
    at Object.fs.closeSync (fs.js:550:18)
    at Object.closeSync (E:\app\node_modules\graceful-fs\graceful-fs.js:51:27)
    at E:\app\node_modules\meteor-desktop\lib\electronBuilder.js:188:28
    at FSReqWrap.oncomplete (fs.js:114:15)
```

My target is nsis too.  I'm confused by the error because I do not find the lib folder under  E:\app\node_modules\meteor-desktop

**Comment by KoenLav** [comment]
@wojtkowiak our issue seems to be fixed!

@enuoCM please create another thread for your issue.
