### ISSUE TITLE
[V0.13.0] Fail to build nsis installer

### ISSUE THREAD

**Issue by enuoCM** [wojtkowiak/meteor-desktop#149]
When running v0.13.0 with `npm run desktop -- build-installer` I receive the following error:

```
INFO  meteorApp:  meteor build finished
INFO  electronApp:  built
DEBUG  electronBuilder:  calling build from electron-builder
  • electron-builder version=20.0.8
  • effective config config=
                       directories:
                         output: 'E:\app\.desktop-installer'
                         buildResources: build
                         app: 'E:\app\.meteor\desktop-build'
                       win:
                         target: nsis
                       squirrelWindows:
                         iconUrl: 'https://github.com/wojtkowiak/meteor-desktop/blob/beta/scaffold/assets/meteor.ico?raw=true'
                         loadingGif: .desktop/assets/loading.gif
                       icon: .desktop/assets/meteor.ico
                       appId: xxx.app
                       productName: xxx
                       copyright: Copyright ©2017 xxx.
                       compression: maximum
                       nsis:
                         oneClick: false
                         perMachine: true
                         installerIcon: .desktop/assets/meteor.ico
                         installerLanguages: zh_CN
                         language: 2052
                         runAfterFinish: false
                         deleteAppDataOnUninstall: true
                       mac:
                         icon: .desktop/assets/meteor.icns
                         extendInfo:
                           LSUIElement: true
                       dmg:
                         icon: .desktop/assets/meteor.icns
                         background: .desktop/assets/dmgBackground.png
                         iconSize: 54
                         contents:
                           - x: 377
                             'y': 190
                             type: link
                             path: /Applications
                           - x: 63
                             'y': 190
                             type: file
                         window:
                           width: 480
                           height: 300
                       extraResources:
                         - from: private/test
                           to: test/
                           filter:
                             - '**/*'
                       asar: false
                       npmRebuild: true
                       electronVersion: 1.7.12

  • two package.json structure is used devPackageFile=E:\app\package.json appPackageFile=E:\app\.meteor\desktop-build\package.json
  • writing effective config file=.desktop-installer\electron-builder.yaml
DEBUG  electronBuilder:  moving node_modules out, because we have them already in app.asar
mv E:\app\.meteor\desktop-build\node_modules E:\app\.meteor\.desktop_node_modules
TypeError: fd must be a file descriptor
    at Object.fs.closeSync (fs.js:550:18)
    at Object.closeSync (E:\app\node_modules\graceful-fs\graceful-fs.js:51:27)
    at E:\app\node_modules\meteor-desktop\lib\electronBuilder.js:188:28
    at FSReqWrap.oncomplete (fs.js:114:15)
```

**Comment by wojtkowiak** [comment]
Hey,
it should be fixed in `0.13.1`

**Comment by wojtkowiak** [comment]
can this be closed?

**Comment by enuoCM** [comment]
Yes，I verified it on 0.14.3
