### ISSUE TITLE
Error build installer

### ISSUE THREAD

**Issue by almikurniawan** [wojtkowiak/meteor-desktop#165]
I get error when build installer in windows 
* command : npm run desktop -- build-installer --win
* result error : 
DEBUG  electronBuilder:  moving node_modules out, because we have them already in app.asar
mv D:\www_node\iik-kantin-kios-update2\.meteor\desktop-build\node_modules D:\www_node\iik-kantin-kios-update2\.meteor\.desktop_n
ode_modules
ERROR  electronBuilder:  error while building installer:  TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:499:7)
    at InstallerBuilder.getPackagedAppPath (D:\www_node\iik-kantin-kios-update2\node_modules\meteor-desktop\lib\electronBuilder.
js:220:21)
    at InstallerBuilder.wait (D:\www_node\iik-kantin-kios-update2\node_modules\meteor-desktop\lib\electronBuilder.js:236:18)
    at D:\www_node\iik-kantin-kios-update2\node_modules\meteor-desktop\lib\electronBuilder.js:358:37
    at <anonymous>

i dont find the node_module folder under D:\www_node\iik-kantin-kios-update2\.meteor\desktop-build\. Iam confuse by this error.

**Comment by wojtkowiak** [comment]
Hey,
thanks for the report!
Should be fixed in `0.17.2`
