### ISSUE TITLE
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by jmarks-joshua** [wojtkowiak/meteor-desktop#191]
I cannot currently build my app, which is pretty concerning as it's been in production for nearly a year now. 

I've created a simple reproduction git repo. Note that all i did to recreate the error was 

1. "meteor create desktop-invalid-callback"
2. "npm install --save @babel/runtime@7.0.0-beta.55" (meteor create doesn't seem to work without this anymore which seems pretty strange to me)
2. "npm install --save-dev meteor-desktop"
3. "npm run desktop -- init"
4.  added ios to platforms
5. "meteor --mobile-server=http://localhost:3000"
6. "npm run desktop"

[reproduction repo](https://github.com/crippledjosh/desktop-invalid-callback)

I don't know if its an issue with this meteor version that is now the only version that works with this version of windows, or if it is directly related to the meteor-desktop version with windows. But given that some people are still building and that i used to be able to build just fine, i think the windows version is going to be relevant. Or i'm well off the mark, but i can't see any references to having to set a callback in any of your documentation. 

![windows version](https://user-images.githubusercontent.com/2428096/43833572-275a68a6-9b03-11e8-9649-b84032a6d6ec.PNG)
![meteor-desktop error](https://user-images.githubusercontent.com/2428096/43833573-27721bb8-9b03-11e8-953c-6a0142046b8d.PNG)

```
ERROR  meteorApp:  error while trying to download index.html for web.cordova, be sure that you are running a mobile target
or with --mobile-server:  TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:141:11)
    at Object.mkdir (fs.js:720:16)
    at MeteorApp._callee6$ (*project-folder*\node_modules\meteor-desktop\lib
\meteorApp.js:651:20)
    at tryCatch (*project-folder*\node_modules\meteor-desktop\node_modules\r
egenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (*project-folder*\node_modules\meteor-d
esktop\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (*project-folder*\
node_modules\meteor-desktop\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (*project-folder*\node_modules\meteor-desktop\dist\meteorApp.js:38:221)

at _next (*project-folder*\node_modules\meteor-desktop\dist\meteorApp.j
at _next (*project-folder*\node_modules\meteor-desktop\dist\meteorApp
at _next (*project-folder*\node_modules\meteor-desktop\dist\meteorAp
at _next (*project-folder*\node_modules\meteor-desktop\dist\meteor
at _next (*project-folder*\node_modules\meteor-desktop\dist\meteo
at _next (*project-folder*\node_modules\meteor-desktop\dist\mete
at _next (*project-folder*\node_modules\meteor-desktop\dist\met
at _next (*project-folder*\node_modules\meteor-desktop\dist\me
at _next (*project-folder*\node_modules\meteor-deskt
at _next (*project-folder*\node_modules\meteor-desop\dist\meteorApp.js:38:409)
at _next (*project-folder*\node_modules\meteor-desktop\dist\meteorApp.js:38:409)
at process._tickCallback (internal/process/next_tick.js:68:7)
```
Not sure what this last bit is doing the shrinking folder name seems pretty bizarre.

**Comment by wojtkowiak** [comment]
Quick question while I'm on my mobile, are you by any chance using node 10? If so check with node 8

**Comment by crippledjosh** [comment]
Ahhh you're a prince among men, i should have tried different node versions before tbh. Thanks :)

**Comment by wojtkowiak** [comment]
> Ahhh you're a prince among men, i should have tried different node versions before tbh

Well that does not change the fact the it should work with node 10 🙂 Will be fixed in the next release, sorry! I'll leave it open since then.
