### ISSUE TITLE
Callback must be a function, Meteor 1.6.1.3 @ meteor-desktop 1.6.0

### ISSUE THREAD

**Issue by KoenLav** [wojtkowiak/meteor-desktop#194]
When running meteor --mobile-server=http://localhost:3000

And afterwards npm run desktop

I get this error message:

ERROR  meteorApp:  error while trying to download index.html for web.cordova, be sure that you are running a mobile target or with --mobile-server:  TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:135:11)
    at Object.mkdir (fs.js:711:16)
    at MeteorApp._callee6$ (C:\Users\koenl\projects\MrWinston\waiter\node_modules\meteor-desktop\lib\meteorApp.js:651:20)
    at tryCatch (C:\Users\koenl\projects\MrWinston\waiter\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\Users\koenl\projects\MrWinston\waiter\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\koenl\projects\MrWinston\waiter\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (C:\Users\koenl\projects\MrWinston\waiter\node_modules\meteor-desktop\dist\meteorApp.js:38:221)
    at _next (C:\Users\koenl\projects\MrWinston\waiter\node_modules\meteor-desktop\dist\meteorApp.js:38:409)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by KoenLav** [comment]
It seems as if the meteor-desktop process is not able to access the file (because I verified it is being built by Meteor).

Permissions maybe?

Running on Windows 10 x64

**Comment by KoenLav** [comment]
Ah, apparently I had Node 10 installed on my machine rather than 8, and calling fs.mkdir without a callback is no longer supported in Node 10.

Node 8 already renders a deprecation warning:

(node:17004) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

In short: nothing pressing, but might be worth considering later :)

**Comment by KoenLav** [comment]
I see this is already fixed in the v1.7.0 PR.
