### ISSUE TITLE
Quick start guide -> Error: Cannot find module 'babel-preset-es2015'

### ISSUE THREAD

**Issue by maasha** [wojtkowiak/meteor-desktop#198]
I followed the quick start and get:

```
ERROR  electronApp:  error while transpiling or minifying:  { Error: Cannot find module 'babel-preset-es2015' from '/Users/maasha'
    at Function.module.exports [as sync] (/Users/maasha/install/src/maasha.dk/node_modules/resolve/lib/sync.js:40:15)
    at resolveStandardizedName (/Users/maasha/install/src/maasha.dk/node_modules/@babel/core/lib/config/files/plugins.js:78:29)
    at resolvePreset (/Users/maasha/install/src/maasha.dk/node_modules/@babel/core/lib/config/files/plugins.js:31:10)
    at loadPreset (/Users/maasha/install/src/maasha.dk/node_modules/@babel/core/lib/config/files/plugins.js:50:18)
    at createDescriptor (/Users/maasha/install/src/maasha.dk/node_modules/@babel/core/lib/config/config-descriptors.js:135:21)
    at /Users/maasha/install/src/maasha.dk/node_modules/@babel/core/lib/config/config-descriptors.js:101:12
    at Array.map (<anonymous>)
    at createDescriptors (/Users/maasha/install/src/maasha.dk/node_modules/@babel/core/lib/config/config-descriptors.js:100:27)
    at createPresetDescriptors (/Users/maasha/install/src/maasha.dk/node_modules/@babel/core/lib/config/config-descriptors.js:92:10)
    at /Users/maasha/install/src/maasha.dk/node_modules/@babel/core/lib/config/config-descriptors.js:64:19
    at presets (/Users/maasha/install/src/maasha.dk/node_modules/@babel/core/lib/config/config-descriptors.js:54:25)
    at mergeChainOpts (/Users/maasha/install/src/maasha.dk/node_modules/@babel/core/lib/config/config-chain.js:294:68)
    at /Users/maasha/install/src/maasha.dk/node_modules/@babel/core/lib/config/config-chain.js:247:7
    at buildRootChain (/Users/maasha/install/src/maasha.dk/node_modules/@babel/core/lib/config/config-chain.js:83:20)
    at loadConfig (/Users/maasha/install/src/maasha.dk/node_modules/@babel/core/lib/config/index.js:50:53)
    at transformFileSync (/Users/maasha/install/src/maasha.dk/node_modules/@babel/core/lib/transform-file-sync.js:27:36)
    at /Users/maasha/install/src/maasha.dk/node_modules/meteor-desktop/lib/electronApp.js:867:32
    at Array.forEach (<anonymous>)
    at ElectronApp.forEach (/Users/maasha/install/src/maasha.dk/node_modules/meteor-desktop/lib/electronApp.js:865:15)
    at tryCatch (/Users/maasha/install/src/maasha.dk/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/maasha/install/src/maasha.dk/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/maasha/install/src/maasha.dk/node_modules/regenerator-runtime/runtime.js:114:21) code: 'MODULE_NOT_FOUND' }
```

**Comment by wojtkowiak** [comment]
Were you able to resolve it?
What meteor and meteor-desktop are you using? What platform?

**Comment by maasha** [comment]
I resolved the issue by updating Node, Meteor, and npm packages.

(meteor-desktop is awesome!)
