### ISSUE TITLE
Building for Windows isn't working on Mac

### ISSUE THREAD

**Issue by dnish** [wojtkowiak/meteor-desktop#22]
Hey,
I try to built an installer on my Mac machine for Windows devices. I'm running the following command:

<code>npm run desktop -- build-installer --win http://myapp:80</code>

The building proccess aborts with the following error:

```
ERROR  installerBuilder:  error while building installer:  TypeError: it.toLowerCase is not a function
at map.it (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/electron-builder/src/targets/targetFactory.ts:29:72)
at Array.map (native)
at normalizeTargets (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/electron-builder/src/targets/targetFactory.ts:29:59)
at createTargets (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/electron-builder/src/targets/targetFactory.ts:19:19)
at /Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/electron-builder/src/packager.ts:134:41
```

**Comment by wojtkowiak** [comment]
Hey @dnish,

I've reproduced it. Will be fixed in `0.1.4` within 10 hours from now.

**Comment by wojtkowiak** [comment]
`0.1.4` has been released, please check it now.

**Comment by dnish** [comment]
Hey @wojtkowiak,
thanks for the update. The error is gone, but now I get the following one if I try to build for Windows:



```

Downloading electron-v1.4.4-win32-x64.zip
[============================================>] 100.0% of 54.28 MB (4.02 MB/s)
ERROR  installerBuilder:  error while building installer:  Error: Exit code: ENOENT. spawn wine ENOENT
    at /Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/electron-builder/src/util/util.ts:102:16
    at exithandler (child_process.js:213:5)
    at ChildProcess.errorhandler (child_process.js:225:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:202:12)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at exec (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/electron-builder/src/util/util.ts:80:3)
    at /Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/electron-builder/src/winPackager.ts:170:11
From previous event:
    at WinPackager.signAndEditResources (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/electron-builder/out/winPackager.js:239:11)
    at /Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/electron-builder/src/winPackager.ts:178:16
From previous event:
    at WinPackager.postInitApp (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/electron-builder/out/winPackager.js:248:11)
    at /Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/electron-builder/src/platformPackager.ts:243:26
From previous event:
    at /Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/electron-builder/src/packager/dirPackager.ts:58:11
    at next (native)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at pack (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/electron-builder/out/packager/dirPackager.js:43:21)
    at /Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/electron-builder/src/platformPackager.ts:185:11
    at next (native)
From previous event:
    at WinPackager.doPack (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/electron-builder/out/platformPackager.js:295:11)
    at /Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/electron-builder/src/winPackager.ts:119:16
    at next (native)
From previous event:
    at WinPackager.pack (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/electron-builder/out/winPackager.js:192:11)
    at /Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/electron-builder/src/packager.ts:134:22
From previous event:
    at Packager.doBuild (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/electron-builder/out/packager.js:254:11)
    at /Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/electron-builder/src/packager.ts:102:32
    at next (native)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at Packager.build (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/electron-builder/out/packager.js:206:11)
    at /Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/electron-builder/src/builder.ts:234:33
    at next (native)
From previous event:
    at build (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/electron-builder/out/builder.js:81:21)
    at InstallerBuilder._callee$ (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/meteor-desktop/lib/installerBuilder.js:57:19)
    at tryCatch (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/regenerator-runtime/runtime.js:95:21)
    at step (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/meteor-desktop/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/meteor-desktop/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/meteor-desktop/node_modules/core-js/library/modules/es6.promise.js:191:7)
    at InstallerBuilder.<anonymous> (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/meteor-desktop/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at InstallerBuilder.build (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/meteor-desktop/dist/installerBuilder.js:136:29)
    at MeteorDesktop._callee$ (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/meteor-desktop/lib/index.js:124:41)
    at tryCatch (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/regenerator-runtime/runtime.js:95:21)
    at step (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/meteor-desktop/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/meteor-desktop/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at run (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/meteor-desktop/node_modules/core-js/library/modules/es6.promise.js:87:22)
    at /Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/meteor-desktop/node_modules/core-js/library/modules/es6.promise.js:100:28
    at flush (/Users/dennis/Desktop/Entwicklung/yb3/yb-web/node_modules/meteor-desktop/node_modules/core-js/library/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)


```

**Comment by dnish** [comment]
Ah okay, so Wine needs to be installed to build for Windows. I'll try that.

**Comment by dnish** [comment]
Works fine now, thank you very much :)
