### ISSUE TITLE
Support Electron v6

### ISSUE THREAD

**Issue by vblagomir** [wojtkowiak/meteor-desktop#238]
When I have electron installen greater than v4 (v5, v6) I have following error while trying to launch the app:
```
TypeError: electron.protocol.registerStandardSchemes is not a function
    at Object.<anonymous> (/Volumes/dev/test-meteor-desktop/.meteor/desktop-build/app/app.js:19:19)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.extWrap (/Volumes/dev/test-meteor-desktop/.meteor/desktop-build/node_modules/reify/node/compile-hook.js:53:7)
    at Object.extManager (/Volumes/dev/test-meteor-desktop/.meteor/desktop-build/node_modules/reify/node/compile-hook.js:19:12)
    at Object.manager [as .js] (/Volumes/dev/test-meteor-desktop/.meteor/desktop-build/node_modules/reify/node/wrapper.js:108:20)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Volumes/dev/test-meteor-desktop/.meteor/desktop-build/app/index.js:4:1)
```

**Comment by darqs** [comment]
Hello,

this issue should be fixed in next version, for now you can try test your application with https://www.npmjs.com/package/meteor-desktop-test

**Comment by evan-coygo** [comment]
@darqs any ETA for that release?

**Comment by darqs** [comment]
@evan-coygo I don't know when we can do it. I found some problem in meteor plugins (bundler and watcher) and I must check how to fix it.

**Comment by lacymorrow** [comment]
Electron v7 was released a couple of weeks ago

**Comment by dorian-coygo** [comment]
@wojtkowiak or @darqs - Is there any update on when the next release will happen?

**Comment by lacymorrow** [comment]
@darqs would you be willing to add me as a collaborator to the project?

**Comment by darqs** [comment]
@dorian-coygo I don't know when version 2.1.0 will be released
@lacymorrow It isn't my repository

**Comment by lacymorrow** [comment]
@wojtkowiak would you be willing to add me as a collaborator to the project?

My interest is in keeping this project alive and functional.

**Comment by LDubya** [comment]
Hi, I'm also interested in using the latest version of electron with this. Currently, the app packages with electron v2 by default. That's kind of out-dated.

**Comment by dorian-coygo** [comment]
FYI: We started a thread to see if we can get first party support. https://forums.meteor.com/t/meteor-desktop-needs-to-have-first-party-support/51452

@KoenLav @LDubya @lacymorrow . We would love your feedback or vote on it.
