### ISSUE TITLE
Transfer package to Meteor Community

### ISSUE THREAD

**Issue by KoenLav** [wojtkowiak/meteor-desktop#243]
@wojtkowiak would you be open to transfer this package to the Meteor Community?

@all package users, would you be willing to help support this package within Meteor Community?

Please leave a comment here: https://github.com/Meteor-Community-Packages/organization/issues/39

**Comment by lacymorrow** [comment]
Absolutely necessary if this package is to stay alive much longer.

This is running 5(!) versions behind on Electron and is in bad need of updates.

There are production build errors and issues that have not been addressed by the author, I'm strongly considering migrating my projects to another desktop framework because of the lack of support.

**Comment by Ajaay** [comment]
We are also using this in production and definitely uneasy about the length of time this has gone without updates.

**Comment by evan-coygo** [comment]
@wojtkowiak this would be great for the community if you're no longer able to maintain a project of this scope. we're happy to help!

**Comment by a4xrbj1** [comment]
Any update to this? Seems this transfer has gone back to being delayed infinite whilst ElectronJS is now on version 12 and beta is version 13 already.

I've tried to update the packages but it broke as it didn't knew `Desktop`:

`uncaught ReferenceError: Desktop is not defined`

**Comment by KoenLav** [comment]
Electron 12.0 is not supported yet, 11.0 works fine though.

**Comment by a4xrbj1** [comment]
> Electron 12.0 is not supported yet, 11.0 works fine though.

Alsjeblieft, Koen.

We're on the following versions:

    "electron": "^10.1.3",
    "electron-builder": "^22.8.1",
    "electron-notarize": "^1.0.0",
    "electron-rebuild": "^2.2.0",

Could you please post which versions you're running smoothly yourself so that I can at least partially upgrade our Electron app?

Dank u wel,

Andreas

**Comment by KoenLav** [comment]
``
    "electron": "11.3.0",  
    "electron-builder": "^22.10.5",  
    "electron-packager": "^15.2.0",  
    "electron-rebuild": "^2.3.5",  
``

**Comment by a4xrbj1** [comment]
Bedankt, Koen.

However, when I upgrade `electron`, `electron-builder` and `electron-rebuild` to the versions you have posted I get the following errors:

```
parent: Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript source code made to be compatible with Deno] is not compatible with this environment.
        at new Errlop (/Users/andreaswest/Documents/workspace/frontend/node_modules/errlop/edition-es5/index.js:61:18)
        at Object.errtion (/Users/andreaswest/Documents/workspace/frontend/node_modules/editions/edition-es5/util.js:23:14)
        at determineEdition (/Users/andreaswest/Documents/workspace/frontend/node_modules/editions/edition-es5/index.js:301:25)
        at determineEdition (/Users/andreaswest/Documents/workspace/frontend/node_modules/editions/edition-es5/index.js:312:12)
        at solicitEdition (/Users/andreaswest/Documents/workspace/frontend/node_modules/editions/edition-es5/index.js:350:16)
        at Object.requirePackage (/Users/andreaswest/Documents/workspace/frontend/node_modules/editions/edition-es5/index.js:364:9)
        at Object.<anonymous> (/Users/andreaswest/Documents/workspace/frontend/node_modules/istextorbinary/index.cjs:4:38)
        at Module._compile (internal/modules/cjs/loader.js:1151:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
        at Module.load (internal/modules/cjs/loader.js:1000:32)
        at Function.Module._load (internal/modules/cjs/loader.js:899:14)
        at Module.require (internal/modules/cjs/loader.js:1040:19)
        at require (internal/modules/cjs/helpers.js:72:18)
        at Object.<anonymous> (/Users/andreaswest/Documents/workspace/frontend/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
        at Module._compile (internal/modules/cjs/loader.js:1151:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
```

Any idea what this "edition" is referring to and why it mentions TypeScript and Deno?

**Comment by KoenLav** [comment]
I think this error may be unrelated to Electron, seems to be related to: https://deno.land/

I've never seen it before and just verified these versions are running fine for me.

**Comment by KoenLav** [comment]
@a4xrbj1 to fix "Desktop is not defined", I think you should set:


    "webPreferences": {
      "enableRemoteModule": true
    }

In your settings.json (of meteor-desktop)

https://www.electronjs.org/docs/breaking-changes#default-changed-enableremotemodule-defaults-to-false
