### ISSUE TITLE
The Mac App store now rejects all Electron v4 builds. 

### ISSUE THREAD

**Issue by LDubya** [wojtkowiak/meteor-desktop#261]
Submitting an app with Electron v4 results in a rejection citing the use of private APIs, discussed here (https://github.com/electron/electron/issues/20027). It was patched in Electron v5 and v6, but not in any version of v4. If meteor-desktop can't support electrion v5, v6, or a fork of v7 that has been patched to fix this issue, then meteor-desktop can't be used to submit apps to the Mac App Store anymore. 

> 
> Guideline 2.5.1 - Performance - Software Requirements
> 
> Your app includes a version of an SDK from Electron that violates the App Store Review Guidelines. The version of the Electron SDK you are using in your app attempts to hide the use of private APIs. This is a violation Section 2.5.1 of the App Store Review Guidelines.
> 
> Guideline 2.5.1: Apps may only use public APIs.
> 
> Next Steps
> 
> To resolve this issue, please either remove the Electron SDK entirely from your app, or revise your app to utilize a corrected version of the Electron SDK.
> 

I'm also citing this issue (https://github.com/wojtkowiak/meteor-desktop/issues/238), which is similar but supporting Electron v5 (^5.0.13) would also address this.

**Comment by darqs** [comment]
Hi @LDubya, 
you have to make local fork (put all project files to your project) for now from master (it support Electron 5 & 6) or from darqs_2.2.0 (it should working with Electron 7 also). After it you need build it locally (`npm install & npm build` inside meteor-desktop).

If you need builder and watcher, you can use config below to change Meteor plugins directory:
`cross-env METEOR_PACKAGE_DIRS=../path/to/meteor-desktop/plugins/ ...`

**Comment by LDubya** [comment]
Hi @darqs, I'm getting an error with a fresh install of Meteor's "simple todos" app.

1. created a fresh install of meteor simple todos:
```bash
meteor create simple-todos
cd simple-todos
```
2. add cordova platform ios
`meteor add-platform ios`

3. fork meteor-desktop at LDubya/meteor-desktop

4. install the forked master branch of meteor-desktop
`meteor npm install --save-dev LDubya/meteor-desktop`

leads to the following error:
```bash
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /Path/To/simple-todos/node_modules/meteor-desktop/dist/bin/cli.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Path/To/simple-todos/node_modules/meteor-desktop/dist/bin/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

and the package is *not* added to package.json, and the build script is also not added to package.json.

# I also tried... 

downloading the master branch, renaming it to `meteor-desktop`, moving it to the `node_modules` folder of `simple-todos`, then `cd simple-todos/node_modules/meteor-desktop`, then running `npm install` from inside that meteor-desktop folder. That leads to the same error of:

```bash
npm ERR! path /Path/To/simple-todos/node_modules/meteor-desktop/dist/bin/cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Path/To/simple-todos/node_modules/meteor-desktop/dist/bin/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

Ignoring that error and running `npm run build` leads to 
```
Successfully compiled 20 files with Babel.
```

but of course the package is *not* added to package.json, and the build script is also not added to package.json.

running `npm install` again does cause it to say

`[meteor-desktop] successfully added a 'desktop' entry to your package.json scripts section.`

and when viewing simple-todos/package.json, there is a `desktop` npm script entry, but 'meteor-desktop' is not listed as a devDependency, nor really anywhere inside of package.json. There also is no version of electron listed as a devDependency.

running `meteor npm install --save-dev electron@5.0.13` adds the electron package that I need and lists it in devDependencies in package.json. 

but this causes meteor-desktop to be removed from node_modules, and I have to start all over again from the start. I do that again and end up back here.

But of course `meteor-desktop` isn't listed as a dev dependency. After manually adding `"meteor-desktop":"^2"` into package.json as devDependencies and then running running `meteor --mobile-server=127.0.0.1:3000`, meteor runs normally. and then in a new tab `npm run desktop -- init` leads the init script to seemingly run successfully.

But then running `npm run desktop` leads to the following error:

```bash
REMINDER: your Meteor project should be running now on port 3000

INFO  index:  initializing
INFO  electronApp:  scaffolding
VERBOSE  desktop:  checking .desktop existence
WARN  index:  you are using a electron@5.0.13 while the recommended version is 6.0.1, the compatibility version is different, use at your own risk, be sure to report that when submitting issues
VERBOSE  meteorApp:  updating .meteor/.gitignore
VERBOSE  meteorApp:  desktopHCP is enabled, checking for required packages
WARN  meteorManager:  desktopHCP requires some packages that are not added to project, will try to add them now
INFO  meteorManager:  adding packages to meteor project omega:meteor-desktop-watcher@2.1.0 omega:meteor-desktop-bundler@2.1.0
 => Errors while parsing arguments:

While adding package omega:meteor-desktop-watcher@=2.1.0:
error: no such version omega:meteor-desktop-watcher@2.1.0

While adding package omega:meteor-desktop-bundler@=2.1.0:
error: no such version omega:meteor-desktop-bundler@2.1.0

ERROR  electronApp:  error while checking for required packages:  Error: Error: adding packages failed
    at MeteorApp.ensureDesktopHCPPackages (/Path/To/simple-todos/node_modules/meteor-desktop/dist/meteorApp.js:99:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simple-todos@ desktop: `meteor-desktop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the simple-todos@ desktop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I'm running out of ideas =(. How can we make this work with a stock install of meteor's simple-todos?

**Comment by LDubya** [comment]
Update: I've tried it using the darqs_2.2.0 branch as well. Same outcome -- the app will run, but if you sign the app with a sandboxed entitlement (`com.apple.security.app-sandbox = YES`), it will crash on startup with the error `Could not initialize app. Please contact your support. Error code: 1`.  Switching that entitlement to `NO` will enable the .app to run. However, the Mac App store requires that entitlement be set to `YES` since they only accept sandboxed apps.

This is with a vanilla install of Meteor's `simple todos`

**Comment by LDubya** [comment]
Same app-sandbox issue also exists with Electron 6.1.7.

**Comment by darqs** [comment]
I think `Could not initialize app...` is related to starting local server, I will check it in sandbox mode.

**Comment by LDubya** [comment]
Is there a way to disable the need for the meteor app to start a local server? Or does the meteor app need to start a local server just to run client-side? Our meteor app doesn't need to connect to a remote server, it's entirely client-side. No remote connection, using Ground DB as the local database. If we could disable meteor even attempting to start a local server, I think it may run sandboxed.

**Comment by LDubya** [comment]
Update: Disabling Electron's Remote module does not have an effect. Issue still remains. Disabled by:

.desktop/settings.json
```json
"window": {
        "webPreferences" : {
            "enableRemoteModule": false
        }
    }
```

**Comment by LDubya** [comment]
Update: stripped down version of Meteor does not have an effect. Issue still remains. Packages used:

`$ cross-env METEOR_PACKAGE_DIRS=node_modules/meteor-desktop/plugins meteor list` :
```bash
blaze-html-templates          1.1.2  Compile HTML templates into reactive UI with Meteor Blaze
ecmascript                    0.14.0* Compiler plugin that supports ES2015+ in all .js files
es5-shim                      4.8.0  Shims and polyfills to improve ECMAScript 5 support
jquery                        3.0.0  Manipulate the DOM using CSS selectors
meteor                        1.9.3  Core Meteor environment
omega:meteor-desktop-bundler  2.1.0+ Bundles .desktop dir into desktop.asar.
omega:meteor-desktop-watcher  2.1.0+ Watches .desktop dir and triggers rebuilds on file change.
reactive-var                  1.0.11  Reactive variable
shell-server                  0.4.0  Server-side component of the `meteor shell` command.
standard-minifier-css         1.6.0  Standard css minifier used with Meteor apps by default.
standard-minifier-js          2.6.0  Standard javascript minifiers used with Meteor apps by default.
tracker                       1.2.0  Dependency tracker to allow reactive callbacks
typescript                    3.7.2* Compiler plugin that compiles TypeScript and ECMAScript in .ts and .tsx files
underscore                    1.0.10  Collection of small helpers: _.map, _.each, ...
webapp                        1.8.2  Serves a Meteor app over HTTP
```

List of Meteor packages removed (while still enabling the app to run):

```
allow-deny            
autopublish           
autoupdate            
binary-heap           
callback-hook         
ddp                   
ddp-client            
ddp-common            
ddp-server            
geojson-utils         
hot-code-push         
insecure              
launch-screen         
livedata              
meteor-base           
minimongo             
mobile-experience     
mobile-status-bar     
mongo                 
mongo-decimal         
mongo-dev-server      
npm-mongo             
reload                
retry                 
shell-server          
socket-stream-client  
```

So I'm not sure if removing Meteor packages is the way to go

**Comment by darqs** [comment]
I think local server is required, because it provides client files.

**Comment by LDubya** [comment]
K I'm giving it a shot submitting with the 'server' and 'client' entitlements. Hoping that the app store reviewer understands that there are no server connections besides the self-consuming local server that the app spins up.

**Comment by msavin** [comment]
I'm stuck in the same boat, and getting the same crash. It's been over a year, and I might go crazy soon.
 
FWIW, there is a fork of `meteor-desktop` which has a number of bugs fixed:
https://github.com/sharekey/meteor-desktop

I downgraded it to Electron 5.0.13, which should be patched for the private APIs. The v6 release runs three new GPU helper instances, so I avoided it because there appear to be other code signing bugs there. However, even with v5 even getting the DMG to run seems to be a hit or miss, even with code signing disabled.

--

FWIW, I had found a few patches that have helped:
- https://github.com/electron-userland/electron-builder/pull/4548/commits/74a94aaba397ed766f965624b7d27d5ead7929f5
- https://github.com/electron-userland/electron-builder/issues/4151
- https://github.com/electron/electron-osx-sign/issues/192

**Comment by msavin** [comment]
I have noticed that the application makes a request for a file using a relative path, and I wonder if that's where the problem is. Probably, this is a bug with `meteor-desktop`, and I notice @Strangerxxx had fixed similar bugs in his fork.

``````
Sandbox: MyApp(84797) deny(1) file-read-data /Users/max/Documents/GitHub/myapp-app/package.json
Violation:       deny(1) file-read-data /Users/max/Documents/GitHub/myapp-app/package.json 
Process:         MyApp [84797]
Path:            /Users/max/Documents/GitHub/myapp-app/.desktop-installer/mac/MyApp.app/Contents/MacOS/MyApp
Load Address:    0x10c7fe000
Identifier:      ooo.company.app
Version:         8 (1.0.0)
Code Type:       x86_64 (Native)
Parent Process:  launchd [1]
Responsible:     /Users/max/Documents/GitHub/myapp-app/.desktop-installer/mac/MyApp.app/Contents/MacOS/MyApp
User ID:         501

```

**Comment by msavin** [comment]
I have noticed that the application makes a request for a file using a relative path, which is outside of the application bundle. I wonder if that's where the sandbox problem is kicking in. Probably, this is a bug with `meteor-desktop`, and I notice @Strangerxxx had fixed similar bugs in his fork.

```
Sandbox: MyApp(84797) deny(1) file-read-data /Users/max/Documents/GitHub/myapp-app/package.json
Violation:       deny(1) file-read-data /Users/max/Documents/GitHub/myapp-app/package.json 
Process:         MyApp [84797]
Path:            /Users/max/Documents/GitHub/myapp-app/.desktop-installer/mac/MyApp.app/Contents/MacOS/MyApp
Load Address:    0x10c7fe000
Identifier:      ooo.company.app
Version:         8 (1.0.0)
Code Type:       x86_64 (Native)
Parent Process:  launchd [1]
Responsible:     /Users/max/Documents/GitHub/myapp-app/.desktop-installer/mac/MyApp.app/Contents/MacOS/MyApp
User ID:         501
```

Also, it's also getting a lot of denial for files that are with-in app 🤔

```
Sandbox: App(84797) deny(1) file-write-create /Users/max/Documents/GitHub/my-app/.desktop-installer/mac/App.app/Contents/Resources/app/.reify-cache/5b2f15d8f3cee98562d05fb435a01e6b003053c3.js
```

**Comment by msavin** [comment]
@LDubya any luck with the client and server entitlements?

**Comment by LDubya** [comment]
@msavin I was able to get the app to run with the entitlements, but am still in App Store Review limbo. They questioned the server entitlement. I wrote a response, but I also removed the client entitlement since the app still runs without it. Then yesterday they came back and said I need to add the client entitlement in a new build (yep it took them 3 days to write one sentence). This is ridiculous.

**Comment by LDubya** [comment]
@msavin well. this is beyond frustrating. While signing, the package adds the "com.apple.security.application-groups" entitlement, even though it's not listed anywhere in my entitlements files. Because of this, the app is getting rejected. Since it's not included in our entitlement plist files, we're not sure where it's being set, and so we don't know how to prevent the packager from including that entitlement. Any ideas?

**Comment by msavin** [comment]
Yes set it as team ID and bundle ID. For example:

<key>com.apple.security.application-groups</key>
<string>TEAM_ID.com.company.appname</string>

**Comment by LDubya** [comment]
@msavin that is how it's set. Specifically, it's TEAM_ID.appID, exactly how this package sets it. We're not using a third-party app to sign it. The problem is, it looks like Apple wants it gone.

```
Guideline 2.4.5(i) - Performance


Your app incorrectly implements sandboxing, or it contains one or more entitlements with invalid values. Please review the included entitlements and sandboxing documentation and resolve this issues before resubmitting a new binary.

"com.apple.security.application-groups"

Next Steps

For information on common app sandboxing issues, please see Technical Q&A QA1773 Common app sandboxing issues.

See App Sandboxing for links to essential video and documentation to learn how to sandbox your application.

Should you need code-level assistance implementing sandboxing, contact Apple Developer Technical Support.
```

**Comment by msavin** [comment]
🤯

**Comment by msavin** [comment]
Is it in your settings.json file for electron? Probably, electron installer or Meteor-desktop is configuring it from there.

**Comment by LDubya** [comment]
Nope, it's not in any of our settings file. A grep returns nothing of the sort. We only set the sandboxed keys: 

- com.apple.security.network.server
- com.apple.security.network.client
- com.apple.security.app-sandbox

But when the app is built, the main app includes the following keys (additional ones are in bold)

- **com.apple.application-identifier**
- com.apple.security.network.server
- **com.apple.developer.team-identifier
- com.apple.security.application-groups**
- com.apple.security.network.client
- com.apple.security.app-sandbox

So it adds entitlements that we don't tell it to. 

Specifically the following file will force-add the application-group entitlement. It's hard-coded in, with no way to flag it not to do so, because it think it knows what's good for us. 

/node_modules/app-builder-lib/electron-osx-sign/util-entitlements.js

the specific lines of code are:

```javascript
// Init entitlements app group key to array if not exists
  if (!entitlements['com.apple.security.application-groups']) {
    entitlements['com.apple.security.application-groups'] = []
  }
  // Insert app group if not exists
  if (Array.isArray(entitlements['com.apple.security.application-groups']) && entitlements['com.apple.security.application-groups'].indexOf(appIdentifier) === -1) {
    debuglog('`com.apple.security.application-groups` not found in entitlements file, new inserted: ' + appIdentifier)
    entitlements['com.apple.security.application-groups'].push(appIdentifier)
  } else {
    debuglog('`com.apple.security.application-groups` found in entitlements file: ' + appIdentifier)
  }
```

This is also not documented anywhere that I could find, besides a github issue chat where the conversation was about unanimously deciding to add this functionality. Which makes me wonder if it's actually supposed to be there and my Apple reviewer doesn't know what he's doing.

**Comment by LDubya** [comment]
Yeah this is ridiculous. Removing that block of code (and thus preventing the entitlement from being included) prevents the app from running on startup.

**Comment by LDubya** [comment]
K,

Approved with the following entitlements (which I believe are minimum for an Electron app):

- com.apple.security.app-sandbox (set explicitly in your plist)
- com.apple.security.network.client (set explicitly in your plist)
- com.apple.security.network.server (set explicitly in your plist)
- com.apple.application-identifier (set automatically during the packaging process assuming you have the settings json file properly set up)
- com.apple.developer.team-identifier (set automatically during the packaging process...)
- com.apple.security.application-groups (set automatically during the packaging process...)

You need to explain the requirement for the server and client entitlements due to the way electron SDK sets up a local server in order to serve the UI

You need to explain the requirement for the application-groups entitlement due to Electron SDK’s need for using the Mach IPC, which is not normally available to a sandboxed app but is made available via the application-groups entitlement.

Don’t explain those things and lose days going back and forth during review.

**Comment by msavin** [comment]
@ldubya are you setting all these in `entitlements.mas.plist`? Can you please share what that file looks like for you?

**Comment by msavin** [comment]
@darqs now that 2.2.5 is out, do you still recommend using your branch?

**Comment by darqs** [comment]
@msavin Hi, version 2.2.5 should work with Electron >= 7.1.10 || >= 8.0.0. My branch fix some Electron issue for Electron 7.1.8, but now it is not required.

**Comment by LDubya** [comment]
Hey @msavin, that's the final output. You can scan a .app to find its lists of entitlements. Within the settings, some are set in entitlements.mas.plist, and others are set automatically by the builders. I can send you a sample entitelements.mas.plist if needed. 

Would love to get some help from someone with this other issue though: #265

**Comment by msavin** [comment]
@LDubya if you can send the sample plists, along with any code changes you had to make to meteor-desktop/etc, that would be great. I have gone through ten builds already and I think the App Store people are starting to get annoyed.

**Comment by LDubya** [comment]
@msavin 

barebones:

.desktop/entitlements/entitlements.mas.plist
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.network.client</key>
    <true/>
    <key>com.apple.security.network.server</key>
    <true/>
  </dict>
</plist>
```

.desktop/entitlements/entitlements.mas.inherit.plist
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.inherit</key>
    <true/>
  </dict>
</plist>
```

And in your .desktop/settings.json
```js
"builderOptions": {
        "mac": {
            ...
            "type" : "distribution",
            "target" : "mas",
            "entitlements" : ".desktop/entitlements/entitlements.mas.plist",
            "entitlementsInherit" : ".desktop/entitlements/entitlements.mas.inherit.plist",
            "hardenedRuntime" : false,
            "identity" : Developer Identity
        },
}
```

Make sure the script is in your AppRoot/package.json

```js
{
  "scripts": {
    ...
    "desktop": "meteor-desktop"
  }
},
```

Run
```bash
npm run desktop -- build-installer --mac;
```

Should output .app and .pkg in AppRoot/.desktop-installer/mas

**Comment by msavin** [comment]
@LDubya thank you, that was very helpful. Are you passing in anything for `extendInfo`?

Here's what my configuration looks like, going to try again this week. Please let me know if you spot any issues.

settings.json
```
"mac": {
          "type": "distribution",
          "icon": "logo.icns",
          "extendInfo": {
             "ElectronTeamID": "XXX",
             "com.apple.developer.team-identifier": "XXX",
             "com.apple.application-identifier": "XXX.com.corp.app",
             "com.apple.security.application-groups": "XXX.com.corp.app"
           },
          "entitlements": "entitlements.mas.plist",
          "entitlementsInherit": "entitlements.mas.inherit.plist",
          "provisioningProfile": "embedded.provisionprofile",
          "target": ["mas"],
          "bundleVersion": "10",
          "hardenedRuntime": false
      }
```
entitlements.mas.plist
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>com.apple.security.app-sandbox</key>
		<true/>
		<key>com.apple.security.network.server</key>
		<true/>
		<key>com.apple.security.network.client</key>
		<true/>
	</dict>
</plist>
```
entitlements.mas.inherit.plist
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>com.apple.security.app-sandbox</key>
		<true/>
		<key>com.apple.security.inherit</key>
		<true/>
	</dict>
</plist>
```

**Comment by LDubya** [comment]
> @LDubya thank you, that was very helpful. Are you passing in anything for `extendInfo`?

Nope. Full mac for us is:
```json
"mac": {
            "icon": ".desktop/assets/MyIcon.icns",
            "type" : "distribution",
            "darkModeSupport": true,
            "target" : "mas",
            "entitlements" : ".desktop/entitlements/entitlements.mas.plist",
            "entitlementsInherit" : ".desktop/entitlements/entitlements.mas.inherit.plist",
            "hardenedRuntime" : false,
            "identity" : "REDACTED"
        }
```

Your provisioning profiles and other credentials should be installed on your device's keychain, registered on App Store Connect, and will be pulled automatically during signing.

**Comment by msavin** [comment]
@LDubya awesome, thanks.

By the way, it looks like Electron 8 has been patched for MAS

**Comment by msavin** [comment]
Can conform 8.0.2 can be published to Mac App Store with above instructions and the workaround posted [here](https://github.com/electron-userland/electron-builder/issues/4151).

**Comment by linegel** [comment]
@msavin @LDubya we made fork here [sharekey/meteor-desktop](https://github.com/sharekey/meteor-desktop) or [npm](https://www.npmjs.com/package/@sharekey/meteor-desktop) using our repo you will have no problems with the latest version of electron and no need for any workaround

**Comment by LDubya** [comment]
@msavin and @linegel , we've been making updates to the desktop app for the first time in a couple years. It looks like Apple is making it hard to test MAS builds locally, so when we build for MAS, the app doesn't load. This makes it hard to test the production build, which is under tighter restrictions. How are you guys able to test your MAS builds before submitting to Apple? We tried the @sharekey/meteor-desktop build, and can't seem to find a setting to allow for testing production MAS builds.
