### ISSUE TITLE
Cannot read property 'assertVersion' of undefined

### ISSUE THREAD

**Issue by trukhilio** [wojtkowiak/meteor-desktop#263]
Hi! When I'm trying to build the ios bundle in Travis I'm getting this error:
```
Errors prevented bundling:
While processing files with omega:meteor-desktop-bundler (for target web.cordova):
/Users/travis/build/myproject/node_modules/@babel/helper-plugin-utils/lib/index.js:10:14: Cannot read property 'assertVersion' of undefined
at /Users/travis/build/myproject/node_modules/@babel/helper-plugin-utils/lib/index.js:10:14
at packages/meteor-desktop-bundler/bundler.js:816:28
at Function.time (/tools/tool-env/profile.js:305:10)
at MeteorDesktopBundler.processFilesForTarget (packages/meteor-desktop-bundler/bundler.js:499:17)
```
meteor-desktop version is 2.2.4

P.S. works with the 2.0.0

**Comment by wojtkowiak** [comment]
Does it only appear when building IOS? What command do you use to built it?
Can you run it with `METEOR_DESKTOP_DEBUG=1` and paste the results?
Can you paste your package.json deps?

**Comment by gunnartorfis** [comment]
I'm encountering the same issue - I tried using meteor-desktop 2.0.0 & 2.2.5 and meteor version 1.8.3 & 1.9.

I get the issue when running
`meteor run --settings ../settings/settings-development.json --port 3002 ios-device --mobile-server 192.168.1.218`
and 
`meteor --mobile-server=127.0.0.1:3000 --settings ../settings/settings-development.json`

However when trying to run the **Cordova app on iOS/Android**, the log outputs:

```
[meteor-desktop] calculated .desktop hash version is xxx_dev
=> Errors prevented startup:

   While processing files with omega:meteor-desktop-bundler (for target web.cordova):
   /Users/gunnartorfi/Projects/timatal/node_modules/@babel/helper-plugin-utils/lib/index.js:10:14: Cannot read property 'assertVersion' of undefined
```

I'm curious why meteor-desktop is doing anything at all when I'm trying to run the mobile app?

**Comment by gunnartorfis** [comment]
I also get the error when running the normal Meteor web app using
`meteor run --settings ../settings/settings-development.json --port 3002`

I'm kind of lost at the moment. I'll comment if I find out anything useful.

**Comment by gunnartorfis** [comment]
I'm encountering the same issue - I tried using meteor-desktop 2.0.0 & 2.2.5 and meteor version 1.8.3 & 1.9.

I get the issue when running (both on iOS and Android)
First started a mobile server (meteor --mobile-server=127.0.0.1:3000), then 
`meteor run ios --settings ../settings/settings-development.json --port 3002 --mobile-server 192.168.1.218`

I'm curious why meteor-desktop is doing anything at all when I'm trying to run the mobile app?

**Comment by gunnartorfis** [comment]
This is happening for me as well in my CI/CD on Github Actions - deploying only the web part of the application. This happens when running "meteor deploy".

Here is the action's output:

```
Preparing to deploy your app...
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
Node#moveTo was deprecated. Use Container#append.
[meteor-desktop] creating a production build
[meteor-desktop] calculated .desktop hash version is 028b921c351fe768ba2172cfcfe433cd071b11c0_prod

Errors prevented deploying:
While processing files with omega:meteor-desktop-bundler (for target
web.cordova):

/home/runner/work/timatal/timatal/node_modules/@babel/helper-plugin-utils/lib/index.js:10:14:
Cannot read property 'assertVersion' of undefined
at
/home/runner/work/timatal/timatal/node_modules/@babel/helper-plugin-utils/lib/index.js:10:14
at packages/meteor-desktop-bundler/bundler.js:816:28
at Function.time
(/home/runner/.meteor/packages/meteor-tool/.1.9.0.1mtsmz6.qnno++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:284:12)
at MeteorDesktopBundler.processFilesForTarget
(packages/meteor-desktop-bundler/bundler.js:499:17)
```

**Comment by abduljanjua** [comment]
any fix for this issue? facing the same issue when updated to 2.2.5

**Comment by dorian-coygo** [comment]
also have the same issue.
