### ISSUE TITLE
Destroys Cordova building for Android

### ISSUE THREAD

**Issue by dnish** [wojtkowiak/meteor-desktop#33]
Hey,
I'm having some issue if I try to run <code>meteor run android-device</code>. My app crashes and Logcat shows me that class "MainActivity" wasn't found. If I check the built "MainActivity.java", the file is empty. If I remove <code>meteor-desktop</code> from my project, everything works fine again. If I add it then again, my Android app fails with the same error.

Seems like <code>meteor-desktop</code> is doing something with the build proccess.

    While preparing Cordova project for platform Android:
     No Java files found that extend CordovaActivity.

**Comment by wojtkowiak** [comment]
Hey, I will be investigating this tomorrow.
This bug is very strange because I already have two apps built for desktop/ios/android without any problems.
However I saw this error before in another context and it seems to be related to packages from `node_modules` being used by cordova instead of the bundled ones in meteor bundle.
`meteor-desktop` does not interfere in any way with meteor itself so I am 100% sure it is not caused directly by it. 
I will check it out. Would you be able to prepare a simple reproduction of this?
In the meantime please check here https://github.com/meteor/meteor/issues/7145

**Comment by dnish** [comment]
Yeah, I'll try to recreate this on a new project.

    rm -Rf .meteor/local
    meteor remove-platform android
    meteor add-platform android

didn't work for me 😩. I don't get an error but the app doesn't start (it closes immediately if I open it -> MainActivity.java is still empty and Logcat shows the same error).

**Comment by dnish** [comment]
@wojtkowiak The same problems happen on a new Meteor project. 

    meteor npm install --save-dev meteor-desktop
    meteor add-platform android
    meteor run --mobile-server http://127.0.0.1:3000
    npm run desktop -- init
    npm run desktop -- start

Killing server and desktop app


    meteor run android-device

The app closes after open it -> no activity found.

I've added the following Cordova plugins:

```com.napolitano.cordova.plugin.intent@https://github.com/napolitano/cordova-plugin-intent.git#44c520e0e690331880af468d70a59d7b6d37c0f0
cordova-plugin-crosswalk-webview@2.1.0
cordova-plugin-device@1.1.3
cordova-plugin-file-transfer@1.6.0
cordova-plugin-inappbrowser@1.5.0
cordova-plugin-music-controls@https://github.com/homerours/cordova-music-controls-plugin.git#58f27f825ae81f6f4c15e4ddf13cccd87efbd473
cordova-plugin-statusbar@2.2.0
cordova-plugin-whitelist@1.3.0

**Comment by wojtkowiak** [comment]
Thanks @dnish for your time. I can confirm that 'unfortunately' I have managed to reproduce it.
It will take a moment for me to investigate it because I need to modify meteor to track this down. First I need to know where the problem lies.
What is super weird is that I did not encounter it before even though I am building for all platform. Maybe it has something to do with meteor version as both of my project are using not the newest one.

**Comment by dnish** [comment]
Thank you very much @wojtkowiak. Do you know any workaround for this issue so that we can release an update of our desktop and mobile apps? At the moment we aren't able to release any updates, because we don't want to destroy any application on the user side. My first idea was to remove the Meteor packages then do the build and release the web version and app. After that I would add the meteor packages again and build the desktop app. I'm just wondering if this would work, because in this case there wouldn't be a server version on the production server and the desktop build should fail, shouldn't it?

**Comment by wojtkowiak** [comment]
I did not ready your entire message yet - just letting you know that I should have a `0.2.3` version with fix/workaround this evening +/- in 8 hours.

**Comment by wojtkowiak** [comment]
> My first idea was to remove the Meteor packages then do meteor build to release the web version and app. After that I would add the Meteor packages again and build the desktop app. I'm just wondering if this would work, because in this case there wouldn't be a desktop version on the production server and the desktop build should fail, shouldn't it?
Well actually `omega:meteor-desktop-localstorage` is harmless. `bundler` and `watcher` are only used for desktopHCP. So it depends on whether you want to use this feature. If yes then doing a production build without those packages would not be a good idea because it could also block the standard HCP mechanism on desktop apps (not totally sure about that - need to test that scenario).

**Comment by wojtkowiak** [comment]
`0.2.3` was just released - please try it out and let me know if that fixes your issue. You will have to delete the `.meteor/local/cordova-build` or just do `meteor reset` if you can afford clearing the db.

**Comment by dnish** [comment]
Thank you very much @wojtkowiak. I hope I can try it out this evening if we have fixed all issues for the next release.

**Comment by dnish** [comment]
@wojtkowiak Is it possible that HCP stopped working in development with the new update? If I change something, it gets reloaded in the browser, but not in the desktop app. I'm running Meteor with <code>meteor run --mobile-server http://127.0.0.1:3000</code>

**Comment by wojtkowiak** [comment]
Hmm nothing have been touched in HCP,
Please delete `run.log` and `autoupdate.log`. Start the desktop app, make a change in the project, wait a while and then paste the logs here.

Logs are stored in the app data dir. Its location is pasted in the logs when the app starts.
> info: [main] app data dir is: C:\Users\Omega\AppData\Roaming\MyMeteorApp

You can also delete `autoupdate.json` and `versions` dir and see if that helps but anyway I would be interested in investigating what have happened.

**Comment by dnish** [comment]
Sure, I'm running on Mac:

run.log

``` 
2016-12-07T23:06:33.588Z - info: [main] ready fired
2016-12-07T23:06:33.589Z - info: [main] seting autoupdate feed to url: http://127.0.0.1/update/darwin_x64/1.0.0
2016-12-07T23:06:33.594Z - error: [main] autoUpdater reported an error: Error: Could not get code signature for running application
    at Error (native)
    at Function.setUpAutoUpdater (/Users/dennis/Desktop/Entwicklung/myapp3/myapp-web/.meteor/desktop-build/app/squirrel.js:158:25)
    at App.onReady (/Users/dennis/Desktop/Entwicklung/myapp3/myapp-web/.meteor/desktop-build/app/app.js:373:18)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
2016-12-07T23:06:33.594Z - debug: [main] loading plugin: meteor-desktop-splash-screen
2016-12-07T23:06:33.600Z - debug: [main] loading plugin: meteor-desktop-localstorage
2016-12-07T23:06:33.603Z - info: [meteor-desktop-splash-screen] [html] preparing splash screen.
2016-12-07T23:06:33.604Z - info: [meteor-desktop-splash-screen] [html] splash screen prepared.
2016-12-07T23:06:33.604Z - info: [meteor-desktop-splash-screen] [splashWindow] displaying splash screen from file:///Users/dennis/Desktop/Entwicklung/myapp3/myapp-web/.meteor/desktop-build/splash.html
2016-12-07T23:06:33.717Z - debug: [main] loading internal module: autoupdate
2016-12-07T23:06:34.051Z - debug: [main] loading internal module: dummy
2016-12-07T23:06:34.052Z - debug: [main] loading internal module: localServer
2016-12-07T23:06:34.109Z - debug: [main] loading module: example => example
2016-12-07T23:06:34.112Z - debug: [main] loading module: register => register
2016-12-07T23:06:34.136Z - verbose: [autoupdate] initializing autoupdate module
2016-12-07T23:06:34.137Z - info: [autoupdate] created empty autoupdate.json
2016-12-07T23:06:34.138Z - verbose: [autoupdate] trying to read initial bundle version
2016-12-07T23:06:34.138Z - verbose: [autoupdate] [AssetBundle] making bundle object for /Users/dennis/Desktop/Entwicklung/myapp3/myapp-web/.meteor/desktop-build/meteor.asar
2016-12-07T23:06:34.138Z - verbose: [autoupdate] [AssetBundle] loading manifest from /Users/dennis/Desktop/Entwicklung/myapp3/myapp-web/.meteor/desktop-build/meteor.asar
2016-12-07T23:06:34.140Z - debug: [autoupdate] [AssetManifest] 100 entries. (Version: e72745bbca4a19addd2eee037f803e45250d630e)
2016-12-07T23:06:34.140Z - verbose: [autoupdate] [AssetBundle] trying to read desktop version for e72745bbca4a19addd2eee037f803e45250d630e
2016-12-07T23:06:34.140Z - verbose: [autoupdate] [AssetBundle] the desktop version is 5a038fe9b5d41b843c5d3eb8cb5c6d9f5a022aaf
2016-12-07T23:06:34.141Z - info: [autoupdate] detected new bundled version, removing versions directory if it exists
2016-12-07T23:06:34.142Z - info: [autoupdate] created versions dir
2016-12-07T23:06:34.144Z - verbose: [autoupdate] using initial asset bundle
2016-12-07T23:06:34.150Z - debug: [main] desktop loaded
2016-12-07T23:06:34.150Z - info: [localServer] will serve from:  /Users/dennis/Desktop/Entwicklung/myapp3/myapp-web/.meteor/desktop-build/meteor.asar
2016-12-07T23:06:34.159Z - info: [localServer] assigned port 8056
2016-12-07T23:06:34.171Z - verbose: [autoupdate] started startup timer
2016-12-07T23:06:34.171Z - debug: [autoupdate] timer set to 60000
2016-12-07T23:06:34.235Z - info: [meteor-desktop-localstorage] have 0 keys
2016-12-07T23:06:36.801Z - verbose: [meteor-desktop-localstorage] getAll received
2016-12-07T23:06:36.801Z - verbose: [meteor-desktop-localstorage] sent storage to renderer
2016-12-07T23:06:37.449Z - verbose: [autoupdate] startup did complete, stopping startup timer (startup took 3278ms)

```

autoupdate.log

```
{"level":"verbose","message":"[autoupdate] initializing autoupdate module","timestamp":"2016-12-07T23:06:34.136Z"}
{"level":"info","message":"[autoupdate] created empty autoupdate.json","timestamp":"2016-12-07T23:06:34.137Z"}
{"level":"verbose","message":"[autoupdate] trying to read initial bundle version","timestamp":"2016-12-07T23:06:34.138Z"}
{"level":"info","message":"[autoupdate] detected new bundled version, removing versions directory if it exists","timestamp":"2016-12-07T23:06:34.141Z"}
{"level":"info","message":"[autoupdate] created versions dir","timestamp":"2016-12-07T23:06:34.142Z"}
{"level":"verbose","message":"[autoupdate] using initial asset bundle","timestamp":"2016-12-07T23:06:34.144Z"}
{"level":"verbose","message":"[autoupdate] started startup timer","timestamp":"2016-12-07T23:06:34.171Z"}
{"level":"debug","message":"[autoupdate] timer set to 60000","timestamp":"2016-12-07T23:06:34.171Z"}
{"level":"verbose","message":"[autoupdate] startup did complete, stopping startup timer (startup took 3278ms)","timestamp":"2016-12-07T23:06:37.449Z"}

```

**Comment by dnish** [comment]
I also recognized some interesting error message within the desktop console:

```
ddp-client.js?hash=bc32a16…:942 GET http://start/sockjs/info?cb=yax_5bzgzg net::ERR_NAME_NOT_RESOLVEDAbstractXHRObject._start @ ddp-client.js?hash=bc32a16…:942(anonymous function) @ ddp-client.js?hash=bc32a16…:976
```

**Comment by wojtkowiak** [comment]
That part `http://start` is disturbing.
Seems that your desktop build has an invalid ddp url, therefore it does not connect to your meteor server and can not receive update from HCP.

One thing can cause that - did you for example run your desktop with `npm run desktop -- start`? The are only `run` and `just-run` commands so it would be intrepreted as a DDP_URL. Currently the ddp url is not validated in any way so if you type `npm run desktop -- start` it will interpret `start` as a DDP_URL pointing your build to that "url". Of course that is an invalid URL so that is the problem. I will add validation.
Was this the problem? Running just `npm run desktop` or `npm run desktop -- http://127.0.0.1:3000` should solve the problem.

**Comment by dnish** [comment]
@wojtkowiak Oh, I don't know why I've started adding "-- start". Totally forgot that I've only to run <code>meteor run desktop</code> 😂

**Comment by dnish** [comment]
I've to reopen it, now I get the following error dialog within my desktop app:

Error: ENOENT, _desktop.json not found in /Users/dennis/Desktop/Entwicklung/myapp/myapp-web/.meteor/desktop-build/meteor.asar

**Comment by wojtkowiak** [comment]
In the `run.log` there should be a full stack of this error - please post it here.

**Comment by dnish** [comment]
@wojtkowiak parts of the run.log:

```

2016-12-08T00:09:53.412Z - error: [main]  Error: ENOENT, _desktop.json not found in /Users/dennis/Desktop/Entwicklung/myapp3/myapp-web/.meteor/desktop-build/meteor.asar
    at notFoundError (ELECTRON_ASAR.js:120:19)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:188:9)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at AssetBundle.writeDesktopVersion (/Users/dennis/Desktop/Entwicklung/myapp3/myapp-web/.meteor/desktop-build/app/modules/autoupdate/assetBundle.js:175:16)
    at AssetBundleManager.handleDesktopBundle (/Users/dennis/Desktop/Entwicklung/myapp3/myapp-web/.meteor/desktop-build/app/modules/autoupdate/assetBundleManager.js:390:25)
    at AssetBundleManager.didFinishDownloadingAssetBundle (/Users/dennis/Desktop/Entwicklung/myapp3/myapp-web/.meteor/desktop-build/app/modules/autoupdate/assetBundleManager.js:379:14)
    at getDesktopVersion.e (/Users/dennis/Desktop/Entwicklung/myapp3/myapp-web/.meteor/desktop-build/app/modules/autoupdate/assetBundleManager.js:200:26)
    at Request.httpClient.e [as _callback] (/Users/dennis/Desktop/Entwicklung/myapp3/myapp-web/.meteor/desktop-build/app/modules/autoupdate/assetBundleManager.js:131:17)
    at Request.self.callback (/Users/dennis/Desktop/Entwicklung/myapp3/myapp-web/.meteor/desktop-build/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)


```

**Comment by wojtkowiak** [comment]
Ufff, I have managed to reproduce it.
The scenario is tricky - maybe not that uncommon - but I did not test this particular case.
This occurs whens you build desktop and have a meteor in version X.
You make change, version Y gets hot code pushed.
You make change, which reverses changes in version Y, so it is version X back again. HCP is smart enough not to download it once again since it has it already. It does not download it, but this package goes through a part of this process in which normally a file `_desktop.json` is added. This fails because the initial version is bundled into non-writable asar archive.
Fix will be released within 2 hours.

**Comment by wojtkowiak** [comment]
Version `0.2.4` with this fix was just released.

**Comment by wojtkowiak** [comment]
Can this be closed?

**Comment by dnish** [comment]
Hey, yes, this can be closed.

**Comment by crapthings** [comment]
hello i have the same issue like this but i don't have meteor-desktop package

> My app crashes and Logcat shows me that class "MainActivity" wasn't found. If I check the built "MainActivity.java", the file is empty.
