### ISSUE TITLE
Errors when building for Windows on Mac

### ISSUE THREAD

**Issue by Ajaay** [wojtkowiak/meteor-desktop#61]
Hi,

I am getting the following errors when trying to build for Windows on Mac. Note - Mac installer is built with no issues.

```
> meteor-desktop "build-installer" "--win"

METEOR-DESKTOP v0.4.0

package/build-installer implies setting --production, setting it for you
REMINDER: your Meteor project should be running now on port 3000

INFO  index:  initializing
INFO  electronApp:  scaffolding
VERBOSE  desktop:  checking .desktop existence
VERBOSE  meteorApp:  updating .meteor/.gitignore
VERBOSE  meteorApp:  desktopHCP is enabled, checking for required packages
VERBOSE  electronAppScaffold:  clearing desktop-build
VERBOSE  electronAppScaffold:  creating /Users/alex/interview-platform/.meteor/desktop-build/app
VERBOSE  electronAppScaffold:  copying skeleton app
VERBOSE  electronAppScaffold:  writing package.json
VERBOSE  electronApp:  updating package.json fields
DEBUG  electronApp:  writing updated package.json
INFO  electronApp:  updating list of package.json's dependencies
WARN  electronApp:  you are using outdated version 0.0.31 of meteor-desktop-splash-screen, the suggested version to use is 0.1.0
DEBUG  electronApp:  merging settings.json[dependencies]
DEBUG  electronApp:  merging settings.json[plugins]
DEBUG  electronApp:  merging dependencies from modules
DEBUG  electronApp:  writing updated package.json
VERBOSE  electronApp:  calculating compatibility version
DEBUG  electronApp:  meteor-desktop compatibility version is  0.4
DEBUG  electronApp:  .desktop compatibility version is  0
INFO  electronApp:  installing dependencies
DEBUG  electronApp:  running npm prune to wipe unneeded dependencies
VERBOSE  electronApp:  executing npm prune
VERBOSE  electronApp:  executing npm install
WARN  electronApp:  native modules rebuild is turned off, be sure to turn it on if you added any native node modules
INFO  electronApp:  packing skeleton app and node_modules to asar archive
DEBUG  electronApp:  moving node_modules to app dir
DEBUG  electronApp:  packing
DEBUG  electronApp:  moving node_modules back from app dir
DEBUG  electronApp:  deleting source files
VERBOSE  electronApp:  copying .desktop to temporary location
DEBUG  electronApp:  updating settings.json fields
INFO  desktop:  calculating hash version from .desktop contents
INFO  electronApp:  excluding files from packing
INFO  electronApp:  transpiling and uglifying
INFO  electronApp:  packing .desktop to asar
VERBOSE  electronApp:  clearing temporary .desktop
INFO  meteorApp:  checking for any mobile platform
INFO  meteorApp:  building meteor app
DEBUG  meteorApp:  clearing build dir
INFO  meteorApp:  acquiring index.html
(node:13812) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
INFO  meteorApp:  successfully downloaded index.html from running meteor app
VERBOSE  meteorApp:  copying mobile build
INFO  meteorApp:  acquiring manifest.json
INFO  meteorApp:  successfully downloaded manifest.json from running meteor app
INFO  meteorApp:  mobile build copied to electron app
DEBUG  meteorApp:  copy cordova.js to meteor build
INFO  meteorApp:  injecting isDesktop
INFO  meteorApp:  injected successfully
INFO  meteorApp:  packing meteor app to asar archive
VERBOSE  meteorApp:  clearing meteor app after packing
INFO  meteorApp:  meteor build finished
INFO  electronApp:  built
WARN  electronBuilder:  skipping dependencies rebuild because platform is different, if you have native node modules as your app dependencies you should od the build on the target platform only
DEBUG  electronBuilder:  moving node_modules out, because we have them already in app.asar
Packaging for win32 x64 using electron 1.4.14 to .desktop-installer/win-unpacked
DEBUG  electronBuilder:  moving node_modules back
Building Squirrel.Windows for arch x64
ERROR  electronBuilder:  error while building installer:  Error: Exit code: ENOENT. spawn mono ENOENT
    at /Users/alex/interview-platform/node_modules/electron-builder-util/src/util.ts:76:16
    at exithandler (child_process.js:218:5)
    at ChildProcess.errorhandler (child_process.js:230:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at exec (/Users/alex/interview-platform/node_modules/electron-builder-util/src/util.ts:54:3)
    at /Users/alex/interview-platform/node_modules/electron-builder-squirrel-windows/src/squirrelPack.ts:180:16
    at Generator.next (<anonymous>)
From previous event:
    at releasify (/Users/alex/interview-platform/node_modules/electron-builder-squirrel-windows/out/squirrelPack.js:157:22)
    at /Users/alex/interview-platform/node_modules/electron-builder-squirrel-windows/src/squirrelPack.ts:88:30
From previous event:
    at buildInstaller (/Users/alex/interview-platform/node_modules/electron-builder-squirrel-windows/out/squirrelPack.js:62:21)
    at /Users/alex/interview-platform/node_modules/electron-builder-squirrel-windows/src/squirrelWindows.ts:36:11
    at Generator.next (<anonymous>)
From previous event:
    at SquirrelWindowsTarget.build (/Users/alex/interview-platform/node_modules/electron-builder-squirrel-windows/out/squirrelWindows.js:73:11)
    at postAsyncTasks.push.default.map.it (/Users/alex/interview-platform/node_modules/electron-builder/src/platformPackager.ts:107:85)
From previous event:
    at WinPackager.packageInDistributableFormat (/Users/alex/interview-platform/node_modules/electron-builder/src/platformPackager.ts:107:41)
    at /Users/alex/interview-platform/node_modules/electron-builder/src/platformPackager.ts:103:10
From previous event:
    at WinPackager.pack (/Users/alex/interview-platform/node_modules/electron-builder/out/platformPackager.js:172:11)
    at /Users/alex/interview-platform/node_modules/electron-builder/src/packager.ts:161:22
From previous event:
    at Packager.doBuild (/Users/alex/interview-platform/node_modules/electron-builder/out/packager.js:296:11)
    at /Users/alex/interview-platform/node_modules/electron-builder/src/packager.ts:129:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Packager.build (/Users/alex/interview-platform/node_modules/electron-builder/out/packager.js:248:11)
    at /Users/alex/interview-platform/node_modules/electron-builder/src/builder.ts:250:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/alex/interview-platform/node_modules/electron-builder/out/builder.js:90:21)
    at InstallerBuilder._callee2$ (/Users/alex/interview-platform/node_modules/meteor-desktop/lib/electronBuilder.js:152:19)
    at tryCatch (/Users/alex/interview-platform/node_modules/meteor-desktop/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/Users/alex/interview-platform/node_modules/meteor-desktop/node_modules/regenerator-runtime/runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/alex/interview-platform/node_modules/meteor-desktop/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/Users/alex/interview-platform/node_modules/meteor-desktop/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/alex/interview-platform/node_modules/meteor-desktop/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at F (/Users/alex/interview-platform/node_modules/meteor-desktop/node_modules/core-js/library/modules/_export.js:35:28)
    at InstallerBuilder.<anonymous> (/Users/alex/interview-platform/node_modules/meteor-desktop/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at InstallerBuilder.build (/Users/alex/interview-platform/node_modules/meteor-desktop/dist/electronBuilder.js:272:30)
    at MeteorDesktop._callee$ (/Users/alex/interview-platform/node_modules/meteor-desktop/lib/index.js:125:40)
    at tryCatch (/Users/alex/interview-platform/node_modules/meteor-desktop/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/Users/alex/interview-platform/node_modules/meteor-desktop/node_modules/regenerator-runtime/runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/alex/interview-platform/node_modules/meteor-desktop/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/Users/alex/interview-platform/node_modules/meteor-desktop/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/alex/interview-platform/node_modules/meteor-desktop/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by wojtkowiak** [comment]
Hey,

do you have wine and mono? 
https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#to-build-app-for-windows-on-macos

**Comment by ethanwillis** [comment]
@wojtkowiak I also noticed this same issue the other day when trying to build for windows on Mac for the first time. I believe I have wine and mono installed. I will double check and post an update.

**Comment by Ajaay** [comment]
Hey - Yep this was due to not having mono installed! All sorted now thanks.
