### ISSUE TITLE
no longer able to build on 0.5.3

### ISSUE THREAD

**Issue by tzapu** [wojtkowiak/meteor-desktop#67]
no idea what the issue might be, after update from 0.4 to 0.5.3 all builds fail.

here s the log
```
INFO  meteorApp:  meteor build finished
INFO  electronApp:  built
WARN  electronBuilder:  skipping dependencies rebuild because platform is different, if you have native node modules as your app dependencies you should od the build on the target platform only
DEBUG  electronBuilder:  moving node_modules out, because we have them already in app.asar
Packaging for win32 x64 using electron 1.4.15 to .desktop-installer/win-unpacked
DEBUG  electronBuilder:  moving node_modules back
Building Squirrel.Windows for arch x64
DEBUG  electronBuilder:  calling installOrRebuild from electron-builder for arch x64
Unhandled rejection SyntaxError: Unexpected token ...
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at _load_CancellationToken (/Users/alex/Documents/Work/Node/extracog/node_modules/electron-builder-squirrel-windows/node_modules/electron-builder-util/out/binDownload.js:99:33)
    at /Users/alex/Documents/Work/Node/extracog/node_modules/electron-builder-squirrel-windows/node_modules/electron-builder-util/src/binDownload.ts:53:24
    at next (native)
    at [object Generator].tryCatcher (/Users/alex/Documents/Work/Node/extracog/node_modules/bluebird-lst-c/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/Users/alex/Documents/Work/Node/extracog/node_modules/bluebird-lst-c/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/Users/alex/Documents/Work/Node/extracog/node_modules/bluebird-lst-c/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/Users/alex/Documents/Work/Node/extracog/node_modules/bluebird-lst-c/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/alex/Documents/Work/Node/extracog/node_modules/bluebird-lst-c/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/alex/Documents/Work/Node/extracog/node_modules/bluebird-lst-c/node_modules/bluebird/js/release/promise.js:636:18)
    at /Users/alex/Documents/Work/Node/extracog/node_modules/bluebird-lst-c/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/alex/Documents/Work/Node/extracog/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:35:14
    at FSReqWrap.oncomplete (fs.js:82:15)
From previous event:
    at doGetBin (/Users/alex/Documents/Work/Node/extracog/node_modules/electron-builder-squirrel-windows/node_modules/electron-builder-util/out/binDownload.js:55:21)
    at getBin (/Users/alex/Documents/Work/Node/extracog/node_modules/electron-builder-squirrel-windows/node_modules/electron-builder-util/src/binDownload.ts:24:38)
    at getBinFromBintray (/Users/alex/Documents/Work/Node/extracog/node_modules/electron-builder-squirrel-windows/node_modules/electron-builder-util/src/binDownload.ts:14:10)
    at /Users/alex/Documents/Work/Node/extracog/node_modules/electron-builder-squirrel-windows/src/squirrelWindows.ts:79:25
    at next (native)
From previous event:
    at SquirrelWindowsTarget.computeEffectiveDistOptions (/Users/alex/Documents/Work/Node/extracog/node_modules/electron-builder-squirrel-windows/out/squirrelWindows.js:126:11)
    at /Users/alex/Documents/Work/Node/extracog/node_modules/electron-builder-squirrel-windows/src/squirrelWindows.ts:35:36
    at next (native)
From previous event:
    at SquirrelWindowsTarget.build (/Users/alex/Documents/Work/Node/extracog/node_modules/electron-builder-squirrel-windows/out/squirrelWindows.js:74:11)
    at /Users/alex/Documents/Work/Node/extracog/node_modules/electron-builder/src/platformPackager.ts:103:85
From previous event:
    at WinPackager.packageInDistributableFormat (/Users/alex/Documents/Work/Node/extracog/node_modules/electron-builder/src/platformPackager.ts:103:41)
    at /Users/alex/Documents/Work/Node/extracog/node_modules/electron-builder/src/platformPackager.ts:99:10
From previous event:
    at WinPackager.pack (/Users/alex/Documents/Work/Node/extracog/node_modules/electron-builder/out/platformPackager.js:160:11)
    at /Users/alex/Documents/Work/Node/extracog/node_modules/electron-builder/src/packager.ts:210:22
From previous event:
    at Packager.doBuild (/Users/alex/Documents/Work/Node/extracog/node_modules/electron-builder/out/packager.js:335:11)
    at /Users/alex/Documents/Work/Node/extracog/node_modules/electron-builder/src/packager.ts:151:38
    at next (native)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Packager.build (/Users/alex/Documents/Work/Node/extracog/node_modules/electron-builder/out/packager.js:261:11)
    at /Users/alex/Documents/Work/Node/extracog/node_modules/electron-builder/src/builder.ts:214:40
    at next (native)
From previous event:
    at build (/Users/alex/Documents/Work/Node/extracog/node_modules/electron-builder/out/builder.js:63:21)
    at InstallerBuilder._callee2$ (/Users/alex/Documents/Work/Node/extracog/node_modules/meteor-desktop/lib/electronBuilder.js:157:19)
    at tryCatch (/Users/alex/Documents/Work/Node/extracog/node_modules/meteor-desktop/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/alex/Documents/Work/Node/extracog/node_modules/meteor-desktop/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/alex/Documents/Work/Node/extracog/node_modules/meteor-desktop/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/Users/alex/Documents/Work/Node/extracog/node_modules/meteor-desktop/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/alex/Documents/Work/Node/extracog/node_modules/meteor-desktop/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (/Users/alex/Documents/Work/Node/extracog/node_modules/meteor-desktop/node_modules/core-js/library/modules/es6.promise.js:191:7)
    at InstallerBuilder.<anonymous> (/Users/alex/Documents/Work/Node/extracog/node_modules/meteor-desktop/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at InstallerBuilder.build (/Users/alex/Documents/Work/Node/extracog/node_modules/meteor-desktop/dist/electronBuilder.js:269:30)
    at MeteorDesktop._callee$ (/Users/alex/Documents/Work/Node/extracog/node_modules/meteor-desktop/lib/index.js:125:40)
    at tryCatch (/Users/alex/Documents/Work/Node/extracog/node_modules/meteor-desktop/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/alex/Documents/Work/Node/extracog/node_modules/meteor-desktop/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/alex/Documents/Work/Node/extracog/node_modules/meteor-desktop/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/Users/alex/Documents/Work/Node/extracog/node_modules/meteor-desktop/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/alex/Documents/Work/Node/extracog/node_modules/meteor-desktop/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at run (/Users/alex/Documents/Work/Node/extracog/node_modules/meteor-desktop/node_modules/core-js/library/modules/es6.promise.js:87:22)
    at /Users/alex/Documents/Work/Node/extracog/node_modules/meteor-desktop/node_modules/core-js/library/modules/es6.promise.js:100:28
    at flush (/Users/alex/Documents/Work/Node/extracog/node_modules/meteor-desktop/node_modules/core-js/library/modules/_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)

No native production dependencies
VERBOSE  electronAppScaffold:  creating /Users/alex/Documents/Work/Node/extracog/.meteor/desktop-build/app
VERBOSE  electronAppScaffold:  copying skeleton app
INFO  electronApp:  packing skeleton app and node_modules to asar archive
DEBUG  electronApp:  moving node_modules to app dir
DEBUG  electronApp:  packing
DEBUG  electronApp:  moving node_modules back from app dir
DEBUG  electronApp:  deleting source files
DEBUG  electronBuilder:  moving node_modules out, because we have them already in app.asar
Packaging for darwin x64 using electron 1.4.15 to .desktop-installer/mac
DEBUG  electronBuilder:  moving node_modules back
Signing app (identity: Developer ID Application: XXXXxXXXXXX)

Building DMG
ERROR  electronBuilder:  error while building installer:  [SyntaxError: Unexpected token ...]

```

not sure what i m missing
cheers

**Comment by wojtkowiak** [comment]
What node version are you using?

**Comment by tzapu** [comment]
hi,

node -v
v6.5.0
npm -v
4.1.2

cheers

**Comment by tzapu** [comment]
same happening with 
node -v
v7.4.0
npm -v
4.3.0

cheers

**Comment by wojtkowiak** [comment]
Quickly tested and I can not reproduce it.
Silly but did you try to remove `node_modules` and install it again? It seems like there is something wrong.

`at _load_CancellationToken (/Users/alex/Documents/Work/Node/extracog/node_modules/electron-builder-squirrel-windows/node_modules/electron-builder-util/out/binDownload.js:99:33)` 
there is a `new Map` so it seems like a node version problem - are you sure you are using `npm run desktop` (`meteor npm run desktop` will fail).

**Comment by tzapu** [comment]
well, sorry about that
i was running meteor npm... 

a rm -rf node_modules and proper command line later and i can build again

thanks
